version: "3.8"
services:
  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - 3000:3000

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb_data: