version: "3.8"
services:
  frontend:
    build: ./packages/frontend
    depends_on:
      - backend
    ports:
      - "8000:8000"
    networks:
      - network-backend
  backend:
    build: ./packages/backend
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - network-backend

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - network-backend

networks:
  network-backend:

volumes:
  mongodb_data: